"""
Pure helpers for building a pre-filled GitHub "new issue" URL from a StatusEvent.

No I/O, no Qt, no side effects — the functions here are unit-testable in
isolation. ``build_github_issue_url`` returns an https://github.com/…
URL that GitHub renders into a pre-filled new-issue form.
"""

from __future__ import annotations

import json
import os
import platform
import sys
from dataclasses import dataclass
from datetime import timezone
from typing import Any
from urllib.parse import quote, urlencode

from services.status_event import StatusEvent, StatusLevel

GITHUB_ISSUE_BASE_URL = "https://github.com/aberrantCode/WinScanOllamaVision/issues/new"

# Map the user-facing feature prefix to a GitHub label. Matches the table in
# _project_specs/status_history.md §6.2.
_AREA_LABELS: dict[str, str] = {
    "Analyze": "area:analyze",
    "Bundle": "area:bundle",
    "Export": "area:export",
    "Import": "area:import",
    "Settings": "area:settings",
    "App": "area:app",
}

_LEVEL_LABELS: dict[StatusLevel, str] = {
    "debug": "severity:debug",
    "info": "severity:info",
    "warn": "severity:warn",
    "error": "severity:error",
}


@dataclass(frozen=True, slots=True)
class IssueTemplate:
    """The three fields GitHub's new-issue form accepts via URL parameters."""

    title: str
    body: str
    labels: list[str]


def _feature_area(feature: str) -> str | None:
    """Return the first token of a feature string (e.g. "Analyze")."""
    if not feature:
        return None
    first = feature.split()[0]
    return first or None


def derive_labels(event: StatusEvent) -> list[str]:
    """Return the GitHub labels an event should be filed with."""
    labels: list[str] = ["auto-filed"]
    area = _feature_area(event.feature)
    if area and area in _AREA_LABELS:
        labels.append(_AREA_LABELS[area])
    labels.append(_LEVEL_LABELS[event.level])
    return labels


def _redact_path(path: str | None) -> str | None:
    """Replace an absolute path with ``<redacted>/<basename>``."""
    if not path:
        return path
    return f"<redacted>/{os.path.basename(path)}"


def _format_context_table(context: dict[str, Any]) -> str:
    """Render a context dict as a GitHub-flavored markdown table."""
    if not context:
        return "_(none)_"
    lines = ["| Key | Value |", "|---|---|"]
    for key in sorted(context.keys()):
        value = context[key]
        if isinstance(value, str) and len(value) > 500:
            value = value[:500] + "…"
        rendered = json.dumps(value, default=str) if not isinstance(value, str) else value
        # Escape pipes so the table doesn't break
        rendered = rendered.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {key} | {rendered} |")
    return "\n".join(lines)


def _system_info(app_version: str) -> dict[str, str]:
    """Collect non-sensitive system info for the issue body."""
    return {
        "app_version": app_version,
        "os": platform.platform(),
        "python": sys.version.split()[0],
    }


def build_issue_body(
    event: StatusEvent,
    *,
    app_version: str,
    redact_paths: bool = True,
    include_traceback: bool = True,
    include_system_info: bool = True,
    extra_system_context: dict[str, str] | None = None,
) -> str:
    """Build the Markdown body of a GitHub issue from a StatusEvent.

    Pure function — no I/O, no mutation. Exposed so tests can assert on
    every byte of the rendered output.
    """
    file_path_display = (
        _redact_path(event.file_path) if redact_paths else event.file_path
    ) or "_(none)_"

    # ISO-8601 UTC with seconds precision
    ts = event.occurred_at
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    when_utc = ts.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    context_table = _format_context_table(event.context)

    parts: list[str] = [
        "<!-- Auto-generated by WinScanLLM Status History -->",
        "",
        "## What I was doing",
        "*(Please describe what you clicked or were trying to accomplish.)*",
        "",
        "## What happened",
        event.title,
        "",
        "## Event details",
        f"- **Feature:** {event.feature}",
        f"- **When:** {when_utc}",
        f"- **Severity:** {event.level}",
        f"- **File:** `{file_path_display}`",
        f"- **Event ID:** `{event.event_id}`",
    ]
    if event.correlation_id:
        parts.append(f"- **Correlation ID:** `{event.correlation_id}`")
    if event.source:
        parts.append(f"- **Source:** `{event.source}`")

    parts += [
        "",
        "## Context",
        context_table,
    ]

    if event.detail:
        parts += [
            "",
            "## Details",
            "```",
            event.detail,
            "```",
        ]

    if include_traceback and event.traceback:
        parts += [
            "",
            "<details>",
            "<summary>Traceback</summary>",
            "",
            "```python",
            event.traceback,
            "```",
            "",
            "</details>",
        ]

    if include_system_info:
        info = _system_info(app_version)
        if extra_system_context:
            info = {**info, **extra_system_context}
        parts += [
            "",
            "## System",
        ]
        for key, value in info.items():
            parts.append(f"- **{key}:** {value}")

    parts += [
        "",
        "---",
        '*Filed from WinScanLLM Status History. Edit the "What I was doing" section above, then click **Submit**.*',
    ]
    return "\n".join(parts)


def build_issue_template(
    event: StatusEvent,
    *,
    app_version: str,
    redact_paths: bool = True,
    include_traceback: bool = True,
    include_system_info: bool = True,
    extra_system_context: dict[str, str] | None = None,
) -> IssueTemplate:
    """Build the full IssueTemplate (title + body + labels) for a StatusEvent."""
    return IssueTemplate(
        title=event.title[:200],  # GitHub titles have a length limit in practice
        body=build_issue_body(
            event,
            app_version=app_version,
            redact_paths=redact_paths,
            include_traceback=include_traceback,
            include_system_info=include_system_info,
            extra_system_context=extra_system_context,
        ),
        labels=derive_labels(event),
    )


def build_github_issue_url(
    event: StatusEvent,
    *,
    app_version: str,
    base_url: str = GITHUB_ISSUE_BASE_URL,
    redact_paths: bool = True,
    include_traceback: bool = True,
    include_system_info: bool = True,
    extra_system_context: dict[str, str] | None = None,
) -> str:
    """Return the full URL that opens a pre-filled new-issue form on GitHub."""
    template = build_issue_template(
        event,
        app_version=app_version,
        redact_paths=redact_paths,
        include_traceback=include_traceback,
        include_system_info=include_system_info,
        extra_system_context=extra_system_context,
    )
    # GitHub's form reads "title", "body", and comma-separated "labels".
    params = {
        "title": template.title,
        "body": template.body,
        "labels": ",".join(template.labels),
    }
    # ``urlencode`` uses quote_plus which renders spaces as "+"; GitHub handles
    # both but the '+' form is more compact and standard for this endpoint.
    return f"{base_url}?{urlencode(params, quote_via=quote)}"
